// src/lib/components/bio.svelte
<script lang="ts">
  import Link from "$lib/components/link.svelte";
  import { siteName } from "$lib/constants";
</script>

<div class="text-2xl text-balance">
  <h1 class="inline font-bold">{siteName}</h1><h2
    class="dark:text-neutral-40 inline font-extralight text-neutral-500 before:content-['—']"
  >
    software developer, stock investor/trader, coffee enthusiast. Currently
    working on docs at <Link href="https://clerk.com/home">Clerk</Link>.
  </h2>
</div>

// components/bio.tsx
import { Link } from "@/components/link";

export function Bio() {
  return (
    <div className="text-2xl text-balance">
      <h1 className="inline font-bold">Michael Novotny</h1>
      <h2 className="dark:text-neutral-40 inline font-extralight text-neutral-500 before:content-['—']">
        software developer, stock investor/trader, avid coffee drinker.
        Currently leading content at{" "}
        <Link href="https://vercel.com/home">Vercel</Link>.
      </h2>
    </div>
  );
}
