// app/notes/page.tsx
import fs from "fs";
import path from "path";

import { ArrowTopRightOnSquareIcon } from "@heroicons/react/24/outline";
import Link from "next/link";
import type { Metadata } from "next";

import { FormattedDate } from "@/components/formatted-date";
import { createMetadata } from "@/lib/metadata";

type NoteData = {
  date: string;
  href: string;
  title: string;
};

const externalNotes: NoteData[] = [
  {
    date: "2024-09-04",
    href: "https://vercel.com/blog/whats-new-in-react-19",
    title: "What's new in React 19",
  },
  {
    date: "2023-08-07",
    href: "https://vercel.com/blog/introducing-next-js-commerce-2-0",
    title: "Introducing Next.js Commerce 2.0",
  },
  {
    date: "2022-12-08",
    href: "https://vercel.com/blog/migrating-a-large-open-source-react-application-to-next-js-and-vercel",
    title:
      "Migrating a large, open-source React application to Next.js and Vercel",
  },
];

export const metadata: Metadata = createMetadata({
  description: "A collection of notes, thoughts, and articles.",
  slug: "notes",
  title: "Notes",
});

function getNoteDirectories() {
  const notesDir = path.join(process.cwd(), "app", "(notes)");

  return fs
    .readdirSync(notesDir)
    .filter((dir) => fs.existsSync(path.join(notesDir, dir, "page.mdx")));
}

const linkClassName =
  "group flex flex-col text-neutral-800 no-underline hover:text-neutral-800 sm:flex-row sm:items-baseline sm:gap-4 dark:text-neutral-200 dark:hover:text-neutral-200";

export default async function NotesPage() {
  const directories = getNoteDirectories();

  const notes: NoteData[] = [...externalNotes];

  for (const directory of directories) {
    const mod = await import(`@/app/(notes)/${directory}/page.mdx`);
    const { date, slug, title } = mod.data;

    notes.push({ date, href: `/${slug}`, title });
  }

  notes.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return (
    <>
      <h1 className="text-3xl font-bold tracking-tight">Notes</h1>
      <ul className="mt-8 space-y-4">
        {notes.map((note) => (
          <li key={note.href}>
            {note.href.startsWith("/") ? (
              <Link className={linkClassName} href={note.href}>
                <FormattedDate className="w-28 shrink-0" date={note.date} />
                <span className="group-hover:underline">{note.title}</span>
              </Link>
            ) : (
              <a
                className={linkClassName}
                href={note.href}
                rel="noopener noreferrer nofollow"
              >
                <FormattedDate className="w-28 shrink-0" date={note.date} />
                <span className="group-hover:underline">
                  {note.title.split(" ").slice(0, -1).join(" ")}{" "}
                  <span className="whitespace-nowrap">
                    {note.title.split(" ").at(-1)}
                    <ArrowTopRightOnSquareIcon className="mb-0.5 ml-1.5 inline size-4" />
                  </span>
                  <span className="sr-only">(external link)</span>
                </span>
              </a>
            )}
          </li>
        ))}
      </ul>
    </>
  );
}

// src/routes/notes/+page.svelte
<script lang="ts">
  import FormattedDate from "$lib/components/formatted-date.svelte";
  import Link from "$lib/components/link.svelte";
  import Seo from "$lib/components/seo.svelte";
  import { getNotes } from "$lib/notes";

  const notes = getNotes();

  const linkClassName =
    "group flex flex-col text-neutral-800 no-underline hover:text-neutral-800 sm:flex-row sm:items-baseline sm:gap-4 dark:text-neutral-200 dark:hover:text-neutral-200";
</script>

<Seo
  description="A collection of notes, thoughts, and articles."
  slug="notes"
  title="Notes"
/>

<h1 class="text-3xl font-bold tracking-tight">Notes</h1>
<ul class="mt-8 space-y-4">
  {#each notes as note (note.href)}
    <li>
      {#if note.href.startsWith("/")}
        <Link class={linkClassName} href={note.href}>
          <FormattedDate class="w-28 shrink-0" date={note.date} />
          <span class="group-hover:underline">{note.title}</span>
        </Link>
      {:else}
        <a
          class={linkClassName}
          href={note.href}
          rel="noopener noreferrer nofollow"
        >
          <FormattedDate class="w-28 shrink-0" date={note.date} />
          <span class="group-hover:underline"
            >{note.title.split(" ").slice(0, -1).join(" ")}{" "}<span
              class="whitespace-nowrap"
              >{note.title.split(" ").at(-1)}<svg
                aria-hidden="true"
                class="mb-0.5 ml-1.5 inline size-4"
                data-slot="icon"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg></span
            ><span class="sr-only">(external link)</span></span
          >
        </a>
      {/if}
    </li>
  {/each}
</ul>
