// components/link.tsx
import { default as NextLink } from "next/link";
import type { ComponentPropsWithoutRef } from "react";

import { cn } from "@/lib/classname";

export function Link({
  href,
  children,
  className,
  ...props
}: ComponentPropsWithoutRef<"a">) {
  const classNames = cn(
    "text-blue-500 underline-offset-3 hover:text-blue-500 hover:underline dark:text-blue-400",
    className,
  );

  if (href?.startsWith("/")) {
    return (
      <NextLink className={classNames} href={href} {...props}>
        {children}
      </NextLink>
    );
  }

  if (href?.startsWith("#")) {
    return (
      <a className={classNames} href={href} {...props}>
        {children}
      </a>
    );
  }

  const isAffiliateLink =
    href?.includes("rwrd.io") ||
    href?.includes("join.robinhood.com") ||
    href?.includes("share_your_love=manovotny");

  return (
    <a
      className={classNames}
      href={href}
      rel={
        "noopener noreferrer nofollow" + (isAffiliateLink ? " sponsored" : "")
      }
      {...props}
    >
      {children}
    </a>
  );
}

// src/lib/components/link.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAnchorAttributes } from "svelte/elements";

  import { cn } from "$lib/classname";

  let {
    children,
    class: className,
    href,
    ...rest
  }: HTMLAnchorAttributes & { children?: Snippet } = $props();

  const classNames = $derived(
    cn(
      "text-blue-500 underline-offset-3 hover:text-blue-500 hover:underline dark:text-blue-400",
      className,
    ),
  );

  const isInternal = $derived(href?.startsWith("/") || href?.startsWith("#"));

  const isAffiliateLink = $derived(
    href?.includes("rwrd.io") ||
      href?.includes("join.robinhood.com") ||
      href?.includes("share_your_love=manovotny"),
  );
</script>

{#if isInternal}
  <a class={classNames} {href} {...rest}>{@render children?.()}</a>
{:else}
  <a
    class={classNames}
    {href}
    rel={cn("noopener noreferrer nofollow", { sponsored: isAffiliateLink })}
    {...rest}
  >
    {@render children?.()}
  </a>
{/if}
